import { Category, ServiceProvider } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: '1', name: 'Financial Mentor', iconName: 'TrendingUp', description: 'Wealth accumulation, budget planning & strategic financial growth mentoring.', group: 'Professional & Executive Advisory' },
  { id: '2', name: 'Career Coach', iconName: 'Briefcase', description: 'Strategic executive career pathing, interview preparation, and corporate advisory.', group: 'Professional & Executive Advisory' },
  { id: '3', name: 'Resume & LinkedIn Consultant', iconName: 'FileText', description: 'Elite resume polishing, cover letter review, and LinkedIn optimization.', group: 'Professional & Executive Advisory' },
  { id: '4', name: 'Business Consultant', iconName: 'BarChart2', description: 'Corporate logistics, operational streamlining, and administrative efficiency.', group: 'Professional & Executive Advisory' },
  { id: '5', name: 'Startup Advisor', iconName: 'Rocket', description: 'Angel investment advice, scale strategy, pitch review, and business initiation.', group: 'Professional & Executive Advisory' },
  { id: '6', name: 'Accountability Coach', iconName: 'Target', description: 'Weekly goal setting, structured productivity audits, and habit reinforcement.', group: 'Professional & Executive Advisory' },
  { id: '14', name: 'Language Partner', iconName: 'Globe', description: 'Dynamic conversational practice, accents, and local language learning.', group: 'Professional & Executive Advisory' },
  { id: '18', name: 'Conference Networking Partner', iconName: 'Users', description: 'Logistics companion to maximize professional networking and lead-gathering.', group: 'Professional & Executive Advisory' },

  { id: '7', name: 'Personal Assistant', iconName: 'User', description: 'High-touch personal dispatching, scheduling, errands, and daily administration.', group: 'Administrative & Logistics' },
  { id: '8', name: 'Executive Assistant', iconName: 'ShieldCheck', description: 'In-box management, complex schedule coordination, and luxury client gateway.', group: 'Administrative & Logistics' },
  { id: '26', name: 'Personal Transportation Manager', iconName: 'Car', description: 'Scheduling private chauffeurs, organizing fleet maintenance, and route planning.', group: 'Administrative & Logistics' },
  { id: '27', name: 'Designated Driver (where permitted)', iconName: 'Shield', description: 'Responsible driver to navigate your personal vehicle and bring you home safely.', group: 'Administrative & Logistics' },
  { id: '28', name: 'Chauffeur Service', iconName: 'Sparkles', description: 'Luxury private car dispatch, airport transfers, and bespoke point-to-point transit.', group: 'Administrative & Logistics' },
  { id: '29', name: 'Errand Runner', iconName: 'ShoppingBag', description: 'Efficient pickup and delivery of parcels, laundry, dry cleaning, and mail.', group: 'Administrative & Logistics' },
  { id: '63', name: 'Research Assistant', iconName: 'Search', description: 'Information gathering, academic or market reviews, and summarized databases.', group: 'Administrative & Logistics' },
  { id: '64', name: 'Virtual Assistant', iconName: 'Mail', description: 'Inbox gating, meeting scheduling, digital organization, and customer support.', group: 'Administrative & Logistics' },
  { id: '65', name: 'Remote Administrative Support', iconName: 'Database', description: 'Secure digital bookkeeping, database entry, and high-volume email templates.', group: 'Administrative & Logistics' },

  { id: '9', name: 'Travel Assistant', iconName: 'Compass', description: 'Bilingual support, travel logistics management, and premium accompanying service.', group: 'Travel & Concierge' },
  { id: '10', name: 'Travel Planner', iconName: 'Map', description: 'Exquisite customized itineraries, elite hotel/flight planning, and navigation routing.', group: 'Travel & Concierge' },
  { id: '11', name: 'Local City Guide', iconName: 'MapPin', description: 'Personalized walking tours, secret spots, and curated restaurant guides.', group: 'Travel & Concierge' },
  { id: '12', name: 'Airport Concierge', iconName: 'Plane', description: 'Baggage claim support, terminal routing, premium lounge booking, and escorting.', group: 'Travel & Concierge' },
  { id: '13', name: 'Vacation Companion', iconName: 'Sun', description: 'Charming companion for travel adventures, cruises, and resort stays.', group: 'Travel & Concierge' },
  { id: '70', name: 'Museum or Historical Tour Guide', iconName: 'Compass', description: 'Insightful historical storytelling, local monument tours, and cultural context.', group: 'Travel & Concierge' },

  { id: '15', name: 'Event Companion', iconName: 'UserCheck', description: 'Aesthetic accompanying companion for elite galas, mixers, and dynamic mixers.', group: 'Events & Social Life' },
  { id: '16', name: 'Wedding Guest', iconName: 'Heart', description: 'Sophisticated companion to accompany you or represent your circle at weddings.', group: 'Events & Social Life' },
  { id: '17', name: 'Gala or Charity Event Guest', iconName: 'Award', description: 'Charming companion with perfect etiquette for non-profit banquets.', group: 'Events & Social Life' },
  { id: '19', name: 'VIP Guest Appearance', iconName: 'Crown', description: 'High-profile, prestigious attendee to elevate the vibe of private gatherings.', group: 'Events & Social Life' },
  { id: '20', name: 'Museum or Cultural Companion', iconName: 'Palette', description: 'Cultured companion to appreciate art history galleries, theaters, and exhibitions.', group: 'Events & Social Life' },
  { id: '21', name: 'Concert Companion', iconName: 'Music', description: 'Passionate music companion for festivals, live performances, and classical operas.', group: 'Events & Social Life' },
  { id: '22', name: 'Dining Companion', iconName: 'Coffee', description: 'Warm conversationalist for tasting menus, fine dining, and culinary tours.', group: 'Events & Social Life' },
  { id: '25', name: 'Sports Event Companion', iconName: 'Trophy', description: 'Passionate and highly informed sports fan to accompany you to stadium matches.', group: 'Events & Social Life' },
  { id: '69', name: 'Community Volunteer Partner', iconName: 'Users', description: 'Active side-by-side partner for non-profit fundraisers and neighborhood cleanups.', group: 'Events & Social Life' },
  { id: '71', name: 'Nightlife Guide', iconName: 'Sparkles', description: 'Securing VIP guestlists, table entries, and lounge hopping tours.', group: 'Events & Social Life' },

  { id: '30', name: 'Grocery Shopper', iconName: 'ShoppingCart', description: 'Personalized nutrition picking, organic food shopping, and kitchen pantry stock.', group: 'Household & Estates' },
  { id: '31', name: 'Home Organization Specialist', iconName: 'Layout', description: 'Aesthetic interior organization, shelving setups, and systematic sorting.', group: 'Household & Estates' },
  { id: '32', name: 'Decluttering Consultant', iconName: 'Trash2', description: 'Minimalist living guidance, room clearing, and down-sizing assistance.', group: 'Household & Estates' },
  { id: '33', name: 'Moving Assistant', iconName: 'Package', description: 'Careful packing of fragile items, cataloging boxes, and move logistics supervision.', group: 'Household & Estates' },
  { id: '34', name: 'Cleaning Manager', iconName: 'Sparkles', description: 'Supervising home cleaning teams and ensuring five-star housekeeping standards.', group: 'Household & Estates' },
  { id: '35', name: 'Laundry & Wardrobe Organizer', iconName: 'Shirt', description: 'Folding systems, textile care coordination, and seasonal closet rotations.', group: 'Household & Estates' },
  { id: '37', name: 'Interior Decorating Assistant', iconName: 'Home', description: 'Theme selection, accessory sourcing, and spatial arrangement advice.', group: 'Household & Estates' },
  { id: '38', name: 'Pet Sitter', iconName: 'Heart', description: 'In-home pet companionship, night care, feeding, and loving supervision.', group: 'Household & Estates' },
  { id: '39', name: 'Dog Walker', iconName: 'Smile', description: 'Healthy neighborhood walking routines, park play, and leash training support.', group: 'Household & Estates' },
  { id: '40', name: 'Pet Transportation', iconName: 'Car', description: 'Safe transport for your pets to veterinary clinics, grooming salons, and spas.', group: 'Household & Estates' },
  { id: '41', name: 'Pet Exercise Provider', iconName: 'Activity', description: 'Agility exercises, running routines, and active physical play for pets.', group: 'Household & Estates' },
  { id: '42', name: 'House Sitter', iconName: 'Lock', description: 'Security monitoring, plant care, mail collection, and keeping your estate immaculate.', group: 'Household & Estates' },
  { id: '43', name: 'Plant Care Provider', iconName: 'Leaf', description: 'Botanical maintenance, watering, fertilization, and indoor garden care.', group: 'Household & Estates' },
  { id: '47', name: 'Smart Home Setup', iconName: 'Cpu', description: 'Sourcing and setting up voice control assistants, lights, and cameras.', group: 'Household & Estates' },
  { id: '66', name: 'Handyman Coordinator (licensed contractors where required)', iconName: 'Settings', description: 'Sourcing, booking, and supervising vetted home repair and utility professionals.', group: 'Household & Estates' },

  { id: '36', name: 'Closet Stylist', iconName: 'Scissors', description: 'Apparel audit, combination styling, and premium closet planning.', group: 'Creative & Digital Media' },
  { id: '44', name: 'Technology Tutor', iconName: 'BookOpen', description: 'Personal tutorials for computer hardware, programs, and digital workflows.', group: 'Creative & Digital Media' },
  { id: '45', name: 'Computer Setup & Support', iconName: 'Monitor', description: 'Secure Wi-Fi configuration, printer setups, and new desktop optimization.', group: 'Creative & Digital Media' },
  { id: '46', name: 'Smartphone Coach', iconName: 'Smartphone', description: 'App training, mobile cloud backups, and smart phone configuration support.', group: 'Creative & Digital Media' },
  { id: '48', name: 'Photography Assistant', iconName: 'Camera', description: 'Lighting support, digital file organizing, and portrait backdrop coordination.', group: 'Creative & Digital Media' },
  { id: '49', name: 'Social Media Consultant', iconName: 'Share2', description: 'Pacing strategies, audience engagement coaching, and layout audits.', group: 'Creative & Digital Media' },
  { id: '50', name: 'Content Creator', iconName: 'PenTool', description: 'Aesthetic copywriting, storytelling templates, and high-impact digital layouts.', group: 'Creative & Digital Media' },
  { id: '51', name: 'Video Editor', iconName: 'Film', description: 'Video splicing, background music syncing, and cinematic color grading.', group: 'Creative & Digital Media' },
  { id: '52', name: 'Personal Photographer', iconName: 'Camera', description: 'Private high-resolution lifestyle portraits and event photo session packages.', group: 'Creative & Digital Media' },
  { id: '53', name: 'Fashion Stylist', iconName: 'Sparkles', description: 'Custom color analysis, personal aesthetic curation, and outfit matching.', group: 'Creative & Digital Media' },

  { id: '54', name: 'Personal Shopper', iconName: 'ShoppingBag', description: 'Sourcing luxury items, gift picking, and courier delivery management.', group: 'Lifestyle & Shopping' },
  { id: '55', name: 'Grooming Consultant', iconName: 'User', description: 'Tailored style routines, hair/barber references, and premium skincare layouts.', group: 'Lifestyle & Shopping' },
  { id: '62', name: 'Personal Concierge', iconName: 'Key', description: 'Booking secret tables, securing dynamic event tickets, and sourcing rare gifts.', group: 'Lifestyle & Shopping' },

  { id: '23', name: 'Fitness Partner', iconName: 'Dumbbell', description: 'Gym partner for workout sessions, form checking, and active encouragement.', group: 'Wellness & Athletics' },
  { id: '24', name: 'Hiking Partner', iconName: 'Mountain', description: 'Wilderness companion for state park trails, hiking, and dynamic climbing.', group: 'Wellness & Athletics' },
  { id: '56', name: 'Meal Prep Assistant', iconName: 'Utensils', description: 'Healthy dietary portioning, ingredient chopping, and weekly recipe preparation.', group: 'Wellness & Athletics' },
  { id: '57', name: 'Cooking Lessons', iconName: 'Book', description: 'Bespoke culinary instruction for baking, fine dinners, and globally inspired menus.', group: 'Wellness & Athletics' },
  { id: '58', name: 'Wellness Coach', iconName: 'Heart', description: 'Sleep optimization audits, dietary tracking advice, and healthy lifestyle planning.', group: 'Wellness & Athletics' },
  { id: '59', name: 'Meditation Guide', iconName: 'Eye', description: 'Bespoke breathing exercises, mindfulness pacing, and stress-release guidance.', group: 'Wellness & Athletics' },
  { id: '60', name: 'Yoga Instructor', iconName: 'Activity', description: 'Private physical posture adjustments, flow sequences, and flexibility drills.', group: 'Wellness & Athletics' },
  { id: '61', name: 'Massage Referral Coordinator (booking only, not treatment unless licensed)', iconName: 'Calendar', description: 'Arranging and coordinate bookings with licensed and certified local massage therapists.', group: 'Wellness & Athletics' },
  { id: '67', name: 'Senior Companion', iconName: 'Heart', description: 'Empathetic conversation, board games, and gentle walking companions.', group: 'Wellness & Athletics' },
  { id: '68', name: 'Accessibility Companion', iconName: 'ShieldCheck', description: 'Empathetic personal guidance, custom routing, and mobility assistance.', group: 'Wellness & Athletics' },

  { id: '72', name: 'LGBTQ+ Relocation Assistant', iconName: 'Home', description: 'Finding inclusive housing, community neighborhood analysis, and local connections.', group: 'LGBTQ+ Specialties' },
  { id: '73', name: 'Coming-Out Support Peer (non-clinical)', iconName: 'Heart', description: 'Completely private, caring peer space to share identity and life experiences.', group: 'LGBTQ+ Specialties' },
  { id: '74', name: 'Pride Event Guide', iconName: 'Smile', description: 'High-energy accompanying partner for local parades, Pride events, and festivals.', group: 'LGBTQ+ Specialties' },
  { id: '75', name: 'LGBTQ+ Travel Safety Consultant', iconName: 'Shield', description: 'Providing detailed global safety rankings, vetted stays, and inclusive itinerary advice.', group: 'LGBTQ+ Specialties' },
];

export const INITIAL_PROVIDERS: ServiceProvider[] = [];
