import { Category, ServiceProvider } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: '1', name: 'Financial Mentoring', iconName: 'TrendingUp', description: 'Wealth accumulation, business growth & investment planning insights.' },
  { id: '2', name: 'Travel Assistants', iconName: 'Compass', description: 'Bilingual guides, itinerary coordinators & luxury travel support.' },
  { id: '3', name: 'Lifestyle Coaching', iconName: 'Sparkles', description: 'Exquisite advice on styling, elite etiquette & executive presentation.' },
  { id: '4', name: 'Personal Concierge', iconName: 'Key', description: 'Elite table reservations, private aviation booking & premium sourcing.' },
  { id: '5', name: 'Event Companions', iconName: 'UserCheck', description: 'Charming, beautifully presented hosts for charity galas & elite gatherings.' },
  { id: '6', name: 'VIP Guest Appearances', iconName: 'Award', description: 'Influential attendees to elevate dynamic business or social occasions.' },
  { id: '7', name: 'Massage and Wellness', iconName: 'Activity', description: 'Luxury spa treatment & personalized private wellness trainers.' },
  { id: '8', name: 'Business Networking', iconName: 'Briefcase', description: 'High-caliber introduction assistants & business networking hosts.' },
];

export const INITIAL_PROVIDERS: ServiceProvider[] = [
  {
    id: 'prov_1',
    name: 'Alessandra Duval',
    title: 'Luxury Etiquette & Fine Arts Guide',
    bio: 'Sorbonne alumna offering elite presentation guidance, art history companionship for private gallery visits, and bilingual high-society etiquette coaching.',
    rating: 4.9,
    reviewsCount: 18,
    completionRate: 100,
    responseTime: '5 mins',
    repeatCustomerRate: 92,
    categories: ['Lifestyle Coaching', 'Event Companions'],
    pricePerEvent: 350,
    priceUnit: 'hour',
    distanceMiles: 2.4,
    locationName: 'Manhattan, New York',
    isFeatured: true,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    verification: {
      governmentId: 'verified',
      selfie: 'verified',
      phone: 'verified',
      email: 'verified',
      professionalCredential: 'verified',
    },
    verifiedBadge: true,
    availabilityCalendar: ['Monday', 'Tuesday', 'Friday', 'Saturday'],
    reviews: [
      {
        id: 'rev_1',
        providerId: 'prov_1',
        customerId: 'cust_99',
        customerName: 'Marcus Sterling',
        rating: 5,
        comment: 'Alessandra was the perfect companion for the Met gala pre-cocktail party. Extremely articulate and cultured.',
        date: '2026-06-15',
      },
      {
        id: 'rev_2',
        providerId: 'prov_1',
        customerId: 'cust_98',
        customerName: 'Victoria Vanderbilt',
        rating: 4.8,
        comment: 'Outstanding guidance on French classical arts. Highly recommend for high-society outings.',
        date: '2026-06-08',
      }
    ]
  },
  {
    id: 'prov_2',
    name: 'Harrison Sterling',
    title: 'Venture Architect & Ultra-Wealth Mentor',
    bio: 'Former boutique investment partner providing exclusive market coaching, yacht charter itinerary planning, and dynamic financial mentoring for emerging elites.',
    rating: 5.0,
    reviewsCount: 22,
    completionRate: 98,
    responseTime: '15 mins',
    repeatCustomerRate: 88,
    categories: ['Financial Mentoring', 'Personal Concierge'],
    pricePerEvent: 800,
    priceUnit: 'day',
    distanceMiles: 4.1,
    locationName: 'Beverly Hills, California',
    isFeatured: true,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    verification: {
      governmentId: 'verified',
      selfie: 'verified',
      phone: 'verified',
      email: 'verified',
      professionalCredential: 'verified',
    },
    verifiedBadge: true,
    availabilityCalendar: ['Wednesday', 'Thursday', 'Saturday', 'Sunday'],
    reviews: [
      {
        id: 'rev_3',
        providerId: 'prov_2',
        customerId: 'cust_97',
        customerName: 'Julian Draxler',
        rating: 5,
        comment: 'His perspective on tech acquisition and real estate portfolios was exceptionally sharp. A true elite mentor.',
        date: '2026-06-12',
      }
    ]
  },
  {
    id: 'prov_3',
    name: 'Elena Rostova',
    title: 'International Travel Liaison & Interpreter',
    bio: 'Fluent in five languages, providing seamless private-aviation airport transfers, bespoke villa provisioning, and security-aware translation and lifestyle support globally.',
    rating: 4.85,
    reviewsCount: 14,
    completionRate: 95,
    responseTime: '8 mins',
    repeatCustomerRate: 75,
    categories: ['Travel Assistants', 'Personal Concierge'],
    pricePerEvent: 500,
    priceUnit: 'event',
    distanceMiles: 7.8,
    locationName: 'Miami Beach, Florida',
    isFeatured: false,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    verification: {
      governmentId: 'verified',
      selfie: 'verified',
      phone: 'verified',
      email: 'verified',
      professionalCredential: 'pending',
    },
    verifiedBadge: true,
    availabilityCalendar: ['Monday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    reviews: [
      {
        id: 'rev_4',
        providerId: 'prov_3',
        customerId: 'cust_96',
        customerName: 'Robert Vance',
        rating: 5,
        comment: 'Elena arranged and hosted our Monaco yacht transit without a single bump. Magnificent multilingual capability.',
        date: '2026-06-02',
      }
    ]
  },
  {
    id: 'prov_4',
    name: 'Damien Mercer',
    title: 'Celebrity Host & VIP Guest Appearance',
    bio: 'Elite event organizer and fashion icon available for high-profile openings, red carpet gala facilitation, charisma coaching, and lifestyle events direction.',
    rating: 4.95,
    reviewsCount: 31,
    completionRate: 100,
    responseTime: '12 mins',
    repeatCustomerRate: 95,
    categories: ['VIP Guest Appearances', 'Business Networking'],
    pricePerEvent: 1200,
    priceUnit: 'event',
    distanceMiles: 1.2,
    locationName: 'SoHo, New York',
    isFeatured: true,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    verification: {
      governmentId: 'verified',
      selfie: 'verified',
      phone: 'verified',
      email: 'verified',
      professionalCredential: 'unverified',
    },
    verifiedBadge: true,
    availabilityCalendar: ['Tuesday', 'Thursday', 'Friday', 'Saturday'],
    reviews: [
      {
        id: 'rev_5',
        providerId: 'prov_4',
        customerId: 'cust_95',
        customerName: 'Sophia de Monaco',
        rating: 5,
        comment: 'Damien transformed our gallery launch with his select list of attendees. Essential asset for VIP circles.',
        date: '2026-06-18',
      }
    ]
  },
  {
    id: 'prov_5',
    name: 'Sienna Sterling',
    title: 'Concierge Wellness & Swedish Therapist',
    bio: 'Exquisite deep tissue wellness treatments, muscle relaxation yoga therapy, and health concierge routines designed specifically for busy executives at 5-star hotel locations.',
    rating: 4.7,
    reviewsCount: 9,
    completionRate: 92,
    responseTime: '30 mins',
    repeatCustomerRate: 60,
    categories: ['Massage and Wellness', 'Lifestyle Coaching'],
    pricePerEvent: 200,
    priceUnit: 'hour',
    distanceMiles: 5.6,
    locationName: 'TriBeCa, New York',
    isFeatured: false,
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200',
    verification: {
      governmentId: 'verified',
      selfie: 'verified',
      phone: 'verified',
      email: 'verified',
      professionalCredential: 'verified',
    },
    verifiedBadge: true,
    availabilityCalendar: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
    reviews: []
  }
];
